apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-add-svc
spec:
  type: ClusterIP
  selector:
    app: {{.Release.Name }}-add-lab
  ports:
  - port: {{ .Values.add.image.servicePort }}
    targetPort: {{ .Values.add.image.containerPort }}  
