common:
  loginServer: acrak123.azurecr.io
  ingressClass: azure-application-gateway

ui:
  replicas: 2
  image:
    name: todomicro-ui
    tag: v2
    containerPort: 80
    servicePort: 80
  host: ui-task.cloudpunk.shop
  
add:
  replicas: 2
  image:
    name: add-task-todo-api
    tag: v1
    containerPort: 8000
    connection_string: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:serverak020201.database.windows.net,1433;Database=db-ak;Uid=Akash123;Pwd=P@$$word@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
    servicePort: 80
  host: add-task.cloudpunk.shop

delete:
  replicas: 2
  image:
    name: delete-task-todo-api
    tag: v1
    containerPort: 8000
    connection_string: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:serverak020201.database.windows.net,1433;Database=db-ak;Uid=Akash123;Pwd=P@$$word@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
    servicePort: 80
  host: del-task.cloudpunk.shop

get:
  replicas: 2
  image:
    name: todo-get-task
    tag: v1
    containerPort: 8000
    connection_string: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:serverak020201.database.windows.net,1433;Database=db-ak;Uid=Akash123;Pwd=P@$$word@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
    servicePort: 80
  host: get-task.cloudpunk.shop

