apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-lab
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-lab
    spec:
      containers:
      - name: {{ .Release.Name }}-todo
        image: {{ .Values.common.loginServer }}/{{ .Values.ui.image.name }}:{{ .Values.ui.image.tag }}
        ports:
        - containerPort: {{ .Values.ui.image.containerPort }}

