apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ui-ingress
spec:
  ingressClassName: {{ .Values.common.ingressClass }}
  rules:
  - host: {{ .Values.ui.host }}
    http:
     paths:
      - backend:
          service:
            name: {{ .Release.Name }}-ui-svc
            port:
              number: {{ .Values.ui.image.servicePort }}
        path: "/"
        pathType: Prefix 
