apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-lab
  ports:
  - port: {{ .Values.ui.image.servicePort }}
    targetPort: {{ .Values.ui.image.containerPort }}
    