apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ .Release.Name }}-get-ingress
spec:
 ingressClassName: {{ .Values.common.ingressClass }}
 rules:
 - host: {{ .Values.get.host }}
   http:
     paths:
      - backend:
          service:
            name: {{ .Release.Name }}-svc
            port:
              number: {{ .Values.get.image.servicePort }}
        path: "/"
        pathType: Prefix 
