apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-delete-ingress
spec:
  ingressClassName: {{ .Values.common.ingressClass }}
  rules:
  - host: {{ .Values.delete.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-svc
            port: 
              number: {{ .Values.delete.image.servicePort}}
        path: "/"         
        pathType: Prefix 
