apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-delete-todo
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-delete-lab
  ports:
  - port: {{ .Values.delete.image.servicePort }}
    targetPort: {{ .Values.delete.image.containerPort }}
